module: KangarooStore
author: Carlos Duclós
github_url: https://github.com/DarkySwift/KangarooStore

theme: fullwidth
clean: true

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Xcode/KangarooStore.xcodeproj, -scheme, KangarooStore-iOS, -destination, platform=iOS Simulator,name=iPhone X, -sdk, iphonesimulator]