language: generic
matrix:
   include:
      # Test Xcode 9.2 / Swift 3.2 - 4.0
       - os: osx
         osx_image: xcode9.2

script:

  # Compile with Xcodex
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean test -project Xcode/KangarooStore.xcodeproj -scheme KangarooStore-iOS -destination "platform=iOS Simulator,name=iPhone X" -sdk iphonesimulator -enableCodeCoverage YES ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'KangarooStore'
